# This is a basic workflow to help you get started with Actions

name: Test

on: [push]

permissions:
  checks: write
  actions: read
  contents: read
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Autograding-Action
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compiler: [clang++-6.0]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: "Install libraries"
        run: |
              sudo apt-get update
              sudo apt-get -y install libboost-date-time-dev clang-6.0

      - name: "Write result"
        run: |
            CLASSROOM_DIR=".github/classroom"
            mkdir -p "$CLASSROOM_DIR"
            cp .github/autograding.json "$CLASSROOM_DIR/"
      
      - name: "[ATTENTION] Check Submission Score Here!"
        uses: education/autograding@v1